# Generated by Django 2.0.3 on 2018-03-29 19:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoOferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarritoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('supercategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baratico.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LineaFacturaOferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=16)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baratico.Factura')),
            ],
        ),
        migrations.CreateModel(
            name='LineaFacturaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=16)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baratico.Factura')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=16)),
                ('tipo', models.CharField(choices=[('D', 'Descuento'), ('P', 'Paquete')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
                ('imagen', models.ImageField(upload_to='')),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=16)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baratico.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoOferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baratico.Oferta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baratico.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Resenna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comentario', models.CharField(max_length=1000)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baratico.Producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=500)),
                ('nombre_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lineafacturaproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baratico.Producto'),
        ),
        migrations.AddField(
            model_name='lineafacturaoferta',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baratico.Oferta'),
        ),
        migrations.AddField(
            model_name='carritoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baratico.Producto'),
        ),
        migrations.AddField(
            model_name='carritoproducto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carritooferta',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baratico.Oferta'),
        ),
        migrations.AddField(
            model_name='carritooferta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='resenna',
            unique_together={('usuario', 'producto')},
        ),
        migrations.AlterUniqueTogether(
            name='productooferta',
            unique_together={('oferta', 'producto')},
        ),
        migrations.AlterUniqueTogether(
            name='lineafacturaproducto',
            unique_together={('factura', 'producto')},
        ),
        migrations.AlterUniqueTogether(
            name='lineafacturaoferta',
            unique_together={('factura', 'oferta')},
        ),
        migrations.AlterUniqueTogether(
            name='carritoproducto',
            unique_together={('usuario', 'producto')},
        ),
        migrations.AlterUniqueTogether(
            name='carritooferta',
            unique_together={('usuario', 'oferta')},
        ),
    ]
