# Generated by Django 2.0.3 on 2018-03-29 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baratico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritooferta',
            name='oferta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baratico.Oferta'),
        ),
    ]
